export default [
  { value: "Ajax", label: "Ajax" },
  { value: "ASP.NET", label: "ASP.NET" },
  { value: "AWS", label: "AWS" },
  { value: "Angular", label: "Angular" },
  { value: "AngularJS", label: "AngularJS" },
  { value: "Assembly", label: "Assembly" },
  { value: "Azure", label: "Azure" },
  { value: "B", label: "B" },
  { value: "BASIC", label: "BASIC" },
  { value: "Bootstrap", label: "Bootstrap" },
  { value: "C", label: "C" },
  { value: "C#", label: "C#" },
  { value: "C++", label: "C++" },
  { value: "COBOL", label: "COBOL" },
  { value: "CSS", label: "CSS" },
  { value: "Dart", label: "Dart" },
  { value: "Deno", label: "Deno" },
  { value: "Django", label: "Django" },
  { value: "Elixir", label: "Elixir" },
  { value: "Ember", label: "Ember" },
  { value: "ExpressJS", label: "ExpressJS" },
  { value: "Firebase", label: "Firebase" },
  { value: "Flask", label: "Flask" },
  { value: "Flutter", label: "Flutter" },
  { value: "Fortran", label: "Fortran" },
  { value: "Gatsby", label: "Gatsby" },
  { value: "Go", label: "Go" },
  { value: "HTML", label: "HTML" },
  { value: "Haskell", label: "Haskell" },
  { value: "Heroku", label: "Heroku" },
  { value: "Java", label: "Java" },
  { value: "JavaScript", label: "JavaScript" },
  { value: "Julia", label: "Julia" },
  { value: "Kotlin", label: "Kotlin" },
  { value: "Laravel", label: "Laravel" },
  { value: "Lisp", label: "Lisp" },
  { value: "Lua", label: "Lua" },
  { value: "MATLAB", label: "MATLAB" },
  { value: "Material UI", label: "Material UI" },
  { value: "MongoDB", label: "MongoDB" },
  { value: "MySQL", label: "MySQL" },
  { value: "Netlify", label: "Netlify" },
  { value: "NextJS", label: "NextJS" },
  { value: "Node js", label: "Node js" },
  { value: "Nuxt", label: "Nuxt" },
  { value: "PHP", label: "PHP" },
  { value: "Pascal", label: "Pascal" },
  { value: "Perl", label: "Perl" },
  { value: "PostgreSQL", label: "PostgreSQL" },
  { value: "Preact", label: "Preact" },
  { value: "Prolog", label: "Prolog" },
  { value: "Python", label: "Python" },
  { value: "R", label: "R" },
  { value: "React", label: "React" },
  { value: "React Native", label: "React Native" },
  { value: "Redis", label: "Redis" },
  { value: "Redux", label: "Redux" },
  { value: "Ruby", label: "Ruby" },
  { value: "Ruby on Rails", label: "Ruby on Rails" },
  { value: "Rust", label: "Rust" },
  { value: "SQL", label: "SQL" },
  { value: "SQLite", label: "SQLite" },
  { value: "Sass", label: "Sass" },
  { value: "Scala", label: "Scala" },
  { value: "SolidJS", label: "SolidJS" },
  { value: "Solidity", label: "Solidity" },
  { value: "Spring", label: "Spring" },
  { value: "Styled Components", label: "Styled Components" },
  { value: "Supabase", label: "Supabase" },
  { value: "Svelte", label: "Svelte" },
  { value: "Swift", label: "Swift" },
  { value: "Tailwind CSS", label: "Tailwind CSS" },
  { value: "TypeScript", label: "TypeScript" },
  { value: "VBScript", label: "VBScript" },
  { value: "Vercel", label: "Vercel" },
  { value: "Visual Basic", label: "Visual Basic" },
  { value: "Vue", label: "Vue" },
  { value: "WebAssembly", label: "WebAssembly" },
  { value: "jQuery", label: "jQuery" },
];
